### ISSUE TITLE
简单加密功能

### ISSUE THREAD

**Issue by Cat7373** [Cat7373/taiji-encode#1]
1. 输入一个密码，通过 Hash 算法将密码转为 Number
2. 用 Number 作为 PRNG 的种子，通过随机数算法打乱码表
3. 由此，不知道输入密码的用户，较难知道码表，即知道算法的情况下，也较难复原原始信息
4. 此算法仅为简单的置换算法，难以对抗专业的密码学攻击，仅供娱乐，专业用途应先通过 AES 等专业算法加密，然后再进行编码
5. 考虑是编解码前打乱码表，还是通过类似 RC4 的方式，动态生成置换关系
6. 加密本身不应对性能产生较大负面影响

**Comment by wallleap** [comment]
好像加密的有点问题：

- 加密随便输入相同的任意字符，例如：`1111`
- 解码的时候只要输入了相同的字符，无论多少个，例如：`1`，都能成功解码

**Comment by Cat7373** [comment]
@wallleap 嗯，这是 RC4 使用密码的方式造成的，每次置换位置使用一位密码，而当密码用光后，则会重新从第一个字开始使用，因此 1 和 1111 的效果是一样的，初始化了 64 位，都相当于 64 个 1

**Comment by Cat7373** [comment]
你会发现 RC4 本身也有相同的问题（同一个字符作为密钥，重复 N 次）

https://cryptii.com/pipes/rc4-encryption

**Comment by wallleap** [comment]
> 你会发现 RC4 本身也有相同的问题（同一个字符作为密钥，重复 N 次）
> 
> https://cryptii.com/pipes/rc4-encryption

嗖嘎

**Comment by Cat7373** [comment]
其实一开始是想基于输入密钥，打乱 taiji 字符列表，后来感觉既然是一个个字生成的，似乎 RC4 这种正好一个个字加密的算法也不错

**Comment by wallleap** [comment]
哦哦，了解了 :call_me_hand:
