### ISSUE TITLE
Web 演示站

### ISSUE THREAD

**Issue by Cat7373** [Cat7373/taiji-encode#3]
1. 用 Vant 做一个 Web 站，方便在手机和电脑上快速测试

**Comment by wallleap** [comment]
Demo：<https://taichi.wallleap.cn>

**Comment by Cat7373** [comment]
真快

**Comment by Cat7373** [comment]
az，怎么停止运行了

**Comment by wallleap** [comment]
> az，怎么停止运行了

换成 vercel 了，服务器带宽太小了，刷新下 dns 缓存试下
